### ISSUE TITLE
trouble with nodejs post method

### ISSUE THREAD

**Issue by rhardaway** [krpeacock/power_strip#1]
Hey Kyle,

this is a very cool example, I've been playing around with Siri and Alexa, and as usual the google capabilities are far more interesting, but also require a lot of tech expertise. I've gotten the IFTTT piece setup, and so my command ('turn on a raspberry pi led') works great. I can see from the npm log that app.js is being called, but the post method exits with 'invalid password' without calling the python script. the problem appears to be that the parameters from the GET req don't get parsed correctly. I'm no get/post/node expert and so I might be missing something, but I am able to use curl to send a post request directly. Let me know what you think, and I can send details/logs/etc.

thanks, bob

**Comment by krpeacock** [comment]
You've got almost everything ready. If you've defined a password in the
.env file, you'll need to attach it to the end of your post request as a
query, as /sw1? password=yourpassword

**Comment by rhardaway** [comment]
ok, so here are more details. The url i have configured is per your instructions:

      http://10.0.0.174:8088/API/switches/sw1?password=google

the post method gets called, but the following test fails, and so invalid password is returned

     if (req.body.password === process.env.PASS){

i check the req.body.password param, and it's value is null (btw, process.env.PASS=google, verifying that my .env file is in play)

I then ran the following curl command from the pi server:

    curl -H "Content-Type: application/json" -X POST -d '{"id":"sw1","command":"on","password":"google"}' http://10.0.0.174:8088/API/switches/sw1

post method is executed again, and this time i can access the params with

    req.body.password=google
    req.body.command=on
    ....

if I add the required params to a GET, I can also access them in the get method:

      http://10.0.0.174:8088/API/switches/sw1?password=google&command=on&id=sw1

So, I am very close: I can either add the execution code to the get method, or configure ifttt with a post method. So maybe IFTTT is generating a POST from the get syntax you configure in the setup?

Definitely think I am missing something: you start by specifying GET syntax in the ifttt url, but also selecting POST there, then in the app.js code get is called first, then post. I am thus confused :-)

**Comment by krpeacock** [comment]
So the structure is legacy from the full react-based website I use in my
home. A get request to the API gets you all the switch data as json, and a
get request gives you the json state of a particular switch.

Post requests will make a change to the state. If it helps you test, you
can disable the check for the password parameter. A simple post request
toggles by default, but the command parameter pets you choose either an on
or off command.

ID  is defined in the route, with sw1, andthe server doesn't currently
check for ID as a query param.

Try making your request through a tool like Postman. Curl requests are
useful, but they are hard to structure when you are figuring out an API for
the first time.

-Kyle

**Comment by rhardaway** [comment]
Very helpful, i wasn't really following how the Switch object is used. I see now that the GET request triggers access of Switch: so if state is off, it gets set to on, and vis-versa. very simple

And so more detail: I said that IFTTT setup was good, well specifically I can tell google home to 'turn on the light' and she responds with the expected 'ok, i'll do that' BUT nothing happens on the node side?? I followed your instructions: select POST method, content=plain/text, no body, and so url is

    http://ipaddressgoeshere/API/switches/sw1?password=yourpasswordhere
or for me:
    http://10.0.0.174:8088/API/switches/sw1?password=google

And so the following curl call is hitting app.js, but google assistant is not ??

**Comment by rhardaway** [comment]
And, when i disable the pw check, it gets into a loop in the post method which i then have to kill.

I realize I am all over the place here, and so I'm really just happy to have your help in explaining how thsi works :-) Thanks!!

**Comment by krpeacock** [comment]
Oh, I see the problem. The 10.*** address you're using is local, but
IFTTT's service requires a publically accessible server and IP address.
You'll need to either set up port forwarding to the pi on your router, or
you'll need to set up webhooks for the pi to listen to an external server.

**Comment by rhardaway** [comment]
Ahh, port forward did the trick!!

So, I have some general observation here about the overall experience so far: my goal is to come up with a very simple way to implement a Smart device and be able to get a home owner up and running with it in minutes. The process we just went thru, while lots of fun, seems pretty raw and requires alot of coding, config, etc. I'm sure the big players will sort this out, and google will continue to evolve their stuff, but right now it's pretty much a science project...

what's your view?

**Comment by krpeacock** [comment]
I agree! There are some great commercial products coming to market that come integrated with multiple assistants. There is a place for science projects, and I'm excited that science projects can benefit from voice controls these days!
